name: Update SDK and Create Pull Request

on:
  repository_dispatch:
    types: [update-sdk]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Install local tools
        run: dotnet tool restore

      - name: Update out of WebApiOne OpenApi
        run: dotnet kiota update -o src/WebApiOne.Client/Sdk

      - name: Update out of WebApiTwo OpenApi
        run: dotnet kiota update -o src/WebApiTwo.Client/Sdk

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT_TRIGGER_PR_WORKFLOW }}
          commit-message: Update SDK
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update-sdk
          title: 'Update SDK'
          body: |
            This PR updates the SDK using the latest OpenAPI definition.
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request